server:
  port: 8080
  contextPath: /KotlinApplication

spring:
  profiles: prod
  datasource:
    sampleapp:
      url: jdbc:postgresql://localhost:5000/SCHOOL_MGT_DB
      username: postgres
      password: 123
      driverClassName: org.postgresql.Driver
      defaultSchema:
      maxPoolSize: 20
      hibernate:
        hbm2ddl.method: update
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL94Dialect